fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.5.0'
    vcsrepo:
      repo: 'git://github.com/puppetlabs/puppetlabs-vcsrepo.git'
      ref: '1.2.0'
    apache:
      repo: 'git://github.com/puppetlabs/puppetlabs-apache.git'
      ref: '1.1.1'
    git:
      repo: 'git://github.com/puppetlabs/puppetlabs-git.git'
      ref: '0.3.0'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.0.0'
  symlinks:
    grafana: "#{source_dir}"
